name: Caching tests

on: [push, pull_request]

jobs:
  test-cache-options:
    name: Test cache options
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - add-to-path: true
            cache-ref: v3.2.0
          - add-to-path: false
            cache-ref: v3

    # Ordering is important here to ensure the correct things are in the
    # correct caches at the correct times.
    #
    # This also relies on having six Cygwin packages that don't have any
    # cross-dependencies (and ideally are small and have few dependencies of
    # their own), so we can distinguish what's cached at what step.
    #
    # We test for the correct behaviour in the following circumstances:
    #
    # option      | saves   | restores
    # ------------+---------+----------
    # disabled    | no (1)  | no (5)
    # enabled     | yes (2) | yes (6)
    # saveonly    | yes (3) | no (7)
    # restoreonly | no (4)  | yes (8)
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # The first Cygwin installation step here must be a "saveonly" step.
      # This means any subsequent steps in this job will pick up a cache
      # created earlier in this job, rather than a cache from a different job.
      - name: Install Cygwin + afio, cache saveonly
        uses: ./
        with:
          packages: afio
          cache: saveonly
          add-to-path: ${{ matrix.add-to-path }}
          cache-ref: ${{ matrix.cache-ref }}

      - name: Delete the Cygwin installation and downloaded packages
        run: |
          Remove-Item -Force -Recurse -Path C:\cygwin
          Remove-Item -Force -Recurse -Path C:\cygwin-packages
          if (Test-Path -Path C:\_package-cache-hashes.csv) {
            Remove-Item -Force -Path C:\_package-cache-hashes.csv
          }

      - name: Install Cygwin + arc, cache enabled
        uses: ./
        with:
          packages: arc
          cache: enabled
          add-to-path: ${{ matrix.add-to-path }}
          cache-ref: ${{ matrix.cache-ref }}

      # This tests 3 + 6
      - name: Ensure afio downloaded
        shell: C:\cygwin\bin\bash.exe --noprofile --norc -e -o pipefail -o igncr {0}
        run: |
          for file in /cygdrive/c/cygwin-packages/*/*/*/*/afio-*.tar.*; do
            [[ -f "$file" ]] && exit 0
          done
          exit 1

      - name: Delete the Cygwin installation and downloaded packages
        run: |
          Remove-Item -Force -Recurse -Path C:\cygwin
          Remove-Item -Force -Recurse -Path C:\cygwin-packages
          if (Test-Path -Path C:\_package-cache-hashes.csv) {
            Remove-Item -Force -Path C:\_package-cache-hashes.csv
          }

      - name: Install Cygwin + argon2, cache restoreonly
        uses: ./
        with:
          packages: argon2
          cache: restoreonly
          add-to-path: ${{ matrix.add-to-path }}
          cache-ref: ${{ matrix.cache-ref }}

      # This tests 2 + 8
      - name: Ensure arc downloaded
        shell: C:\cygwin\bin\bash.exe --noprofile --norc -e -o pipefail -o igncr {0}
        run: |
          for file in /cygdrive/c/cygwin-packages/*/*/*/*/arc-*.tar.*; do
            [[ -f "$file" ]] && exit 0
          done
          exit 1
