name: Full round of cache performance testing

on:
  # These tests are slow, so they don't need to be run regularly.  They also
  # aren't designed to catch problems that will be automatically spotted, but to
  # allow someone to look at the results and confirm that caching improves
  # install times.
  - workflow_dispatch
  # But GitHub is miserable about dispatch actions that aren't on main, and I
  # don't want to put this on main yet, so make it run on pushes after all.
  - push

jobs:
  test-perf-min:
    name: Run perf tests
    uses: ./.github/workflows/cache-perf.yml

  test-perf-cygport:
    name: Run perf tests
    uses: ./.github/workflows/cache-perf.yml
    with:
      # Approximately 140MB as of January 2023
      packages: cygport

  test-perf-tex:
    name: Run perf tests
    # This job will create very big caches.  To avoid that causing a problem
    # with parallel runs leading to caches being evicted, only permit one run
    # of this job at a time.
    concurrency: big-caches
    uses: ./.github/workflows/cache-perf.yml
    with:
      # Approximately 4GB as of January 2023
      packages: >
        dblatex doxygen-latex emacs-auctex emacs-gettext
        geany-plugins-geanylatex gettext gettext-debuginfo gettext-devel
        gettext-doc kf5-kpimtextedit-debuginfo kf5-ktexteditor-debuginfo
        kf5-ktextwidgets-debuginfo latex2rtf latex2rtf-debuginfo latexila
        latexila-debuginfo libboost_context1.60 libboost_context1.63
        libboost_context1.64 libboost_context1.66 libgettextpo-devel
        libgettextpo0 libptexenc-devel libptexenc1 libsynctex-devel libsynctex1
        libsynctex2 libtexlua52-devel libtexlua52_5 libtexlua53-devel
        libtexlua53_5 libtexluajit-devel libtexluajit2 mate-text-editor
        mate-text-editor-devel mate-text-editor-plugins mingw64-i686-gettext
        mingw64-i686-gettext-debuginfo mingw64-x86_64-gettext
        mingw64-x86_64-gettext-debuginfo ocaml-gettext perl-gettext
        perl-gettext-debuginfo perl-Locale-gettext php-gettext preview-latex
        pstotext ruby-gettext ruby-gettext-doc ruby-text ruby-text-doc
        texi2html texinfo texinfo-debuginfo texinfo-tex texlive
        texlive-collection-basic texlive-collection-basic-doc
        texlive-collection-bibtexextra texlive-collection-bibtexextra-doc
        texlive-collection-binextra texlive-collection-binextra-doc
        texlive-collection-context texlive-collection-context-doc
        texlive-collection-fontsextra texlive-collection-fontsextra-doc
        texlive-collection-fontsrecommended
        texlive-collection-fontsrecommended-doc texlive-collection-fontutils
        texlive-collection-fontutils-doc texlive-collection-formatsextra
        texlive-collection-games texlive-collection-genericextra
        texlive-collection-genericextra-doc
        texlive-collection-genericrecommended
        texlive-collection-genericrecommended-doc texlive-collection-htmlxml
        texlive-collection-humanities texlive-collection-humanities-doc
        texlive-collection-langafrican texlive-collection-langarabic
        texlive-collection-langchinese texlive-collection-langcjk
        texlive-collection-langcyrillic texlive-collection-langczechslovak
        texlive-collection-langenglish texlive-collection-langeuropean
        texlive-collection-langfrench texlive-collection-langgerman
        texlive-collection-langgreek texlive-collection-langindic
        texlive-collection-langitalian texlive-collection-langjapanese
        texlive-collection-langkorean texlive-collection-langother
        texlive-collection-langpolish texlive-collection-langportuguese
        texlive-collection-langspanish texlive-collection-latex
        texlive-collection-latex-doc texlive-collection-latexextra
        texlive-collection-latexextra-doc texlive-collection-latexrecommended
        texlive-collection-latexrecommended-doc texlive-collection-luatex
        texlive-collection-luatex-doc texlive-collection-mathextra
        texlive-collection-mathextra-doc texlive-collection-mathscience
        texlive-collection-mathscience-doc texlive-collection-metapost
        texlive-collection-metapost-doc texlive-collection-music
        texlive-collection-music-doc texlive-collection-omega
        texlive-collection-pictures texlive-collection-pictures-doc
        texlive-collection-plainextra texlive-collection-plaingeneric
        texlive-collection-plaingeneric-doc texlive-collection-pstricks
        texlive-collection-pstricks-doc texlive-collection-publishers
        texlive-collection-publishers-doc texlive-collection-science
        texlive-collection-science-doc texlive-collection-xetex
        texlive-collection-xetex-doc texlive-debuginfo untex
