name: Cache performance testing

# Only run manually: the purpose of this test is to check how much (if at all)
# using the caches helps, and that's not something that needs doing often, and
# it is something that's time consuming.
on: workflow_dispatch

jobs:
  # This will populate the cache without using any pre-existing cache, so we
  # can see how long it takes to install without the cache.
  install-without-cache:
    runs-on: windows-latest
    needs: clear-caches
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install a large set of Cygwin packages
        uses: ./
        with:
          packages: >
            biber doxygen evolution kde-dev-utils
            mkvtoolnix-debuginfo nghttp x11vnc
          cache: saveonly

  # Because the cache restore process will prefer caches from the same job,
  # this will always restore the cache created by the install-without-cache
  # job, so we can check what difference using the cache makes.
  install-with-cache:
    runs-on: windows-latest
    needs: install-without-cache
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install a large set of Cygwin packages
        uses: ./
        with:
          packages: >
            biber doxygen evolution kde-dev-utils
            mkvtoolnix-debuginfo nghttp x11vnc
          cache: restoreonly
